version: '3'
services:
  web:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "30000:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=